[tool.poetry]
name = "aoc_2020"
version = "0.1.0"
description = ""
authors = ["Drew O'Kane <rhoslug@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
